# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/

orbs:
  node: circleci/node@4.7
  coveralls: coveralls/coveralls@1.0.6

jobs:
  unit-test:
    docker:
      - image: circleci/node:12
    steps:
      - run:
          name: Delete any old node_modules
          command: |
            rm -rf node_modules/
      - run:
          name: Install truffle (globally)
          command: |
            sudo npm install -g truffle
      - node/install:
      # - run:
      #     name: Install Node dependencies
      #     command: |
      #       sudo npm install
      - run:
          name: Run tests
          command: |
            truffle run coverage

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  test: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - unit-test
